

package AFDEmp_Project_Individual;

import static AFDEmp_Project_Individual.Utils.*;

import java.sql.Date;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;

public class ProjectMain {
    //static Database db;
    //User admin;
    
    
    ProjectMain() {
        //db = new Database();
        //UserCRUD uc= new UserCRUD();
        //admin = new User(); // 
    }
    
    
    public static void main(String[] args) {
        //ProjectMain myProgram = new ProjectMain();
     //   UserCRUD uc= new UserCRUD();
        //uc.viewAllUsers();
        //User auser = new User();
        //String s=uc.getUserByID(9).toString();
        //uc.getUserByID(1).toString2();
        //uc.insertUser("writer3", "1234", "Nick", "Bostrom", "writer");
        //uc.viewAllUsers();
        //Database db = new Database();
        
        //db.connectAndTest(true);
       //db.connect();
       // TODO code application logic here
       //User user = new User();
       //user.id = user.createUser(db, "user3", "pass3", "Max", "Tegmark");
       // user.id = user.deleteUser(db, "user6");
       //Message message = new Message();
       //Timestamp now = Timestamp.valueOf(LocalDateTime.now());
       //message.createMessage(db, now, 4, 3, "message!");
       //db.viewAllMessages(true);
       //requestConfirmation();
       
//       String title = "This is a very important Message :";
//       String s = "Life is a poorly written open world rpg where almost all the reward "
//               + "is generated by weird and repetitive mini games.The problem is that"
//               + " when you neglect the minigames you get depressed, because the big games"
//               + " don't pay out much experiential reward.";
//       
//       String a = "It is weird that we expect school children to understand only 50%–70% of "
//               + "a topic (like calculus) before we move on to one that builds on it. "
//               + "No computer game would have tutorial levels like that. It frustrates all progress.";
////       
//       String d="I believe that our universe must be generated from a simple very short line of code,"
//               + " because a small glitch in the general nonexistence of everything must suffice to "
//               + "produce the accident of everything that exists.";
//     String f="I believe that our universe must be generated from a simple very short line of code,"
//               + " because a small glitch in the general nonexistence of everything must suffice to "
//               + "produce the accident of everything that exists."; 
//       String f = "A nerd is someone who thinks the purpose of communication is submitting one's ideas to peer review.";
//       clearConsole();
//        System.out.println("\n\n\n\n\n");
//        wrapText( "Title: "+title,70,4,'_');
//       System.out.println();
//       wrapText(s,40,50, ' ');
//        pauseExecution();
//         clearConsole();
//        System.out.println("\n\n\n\n\n");
//        wrapText( "Title: "+title,70,4,'_');
//       System.out.println();
//       wrapText(d,40,50, ' ');
//        System.out.println(title);
//        System.out.println(s);
       
       
//       String w="2";
//       int i = Integer.parseInt(s);


        new Menus().loginMenu();
        //new Menus().mainMenu();
    }
    
    
    
}

